//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcCore.Business.DB0
{
    using System;
    using System.Collections.Generic;
    
    public partial class i_Currency
    {
        public int id { get; set; }
        public string name_currency { get; set; }
        public string english_currency { get; set; }
        public string sign { get; set; }
        public string code { get; set; }
        public bool is_use { get; set; }
    }
}
