//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcCore.Business.DB0
{
    using System;
    using System.Collections.Generic;
    
    public partial class i_Lang
    {
        public string lang { get; set; }
        public string area { get; set; }
        public string memo { get; set; }
        public bool isuse { get; set; }
        public byte sort { get; set; }
    }
}
