//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcCore.Business.DB0
{
    using System;
    using System.Collections.Generic;
    
    public partial class i_Parm
    {
        public string ParmName { get; set; }
        public string ParmType { get; set; }
        public string S { get; set; }
        public int I { get; set; }
        public decimal F { get; set; }
        public System.DateTime D { get; set; }
        public bool B { get; set; }
        public string Memo { get; set; }
    }
}
