//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcCore.Business.DB0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Menu()
        {
            this.AspNetRoles = new HashSet<AspNetRoles>();
        }
    
        public int menu_id { get; set; }
        public int parent_menu_id { get; set; }
        public string menu_name { get; set; }
        public string description { get; set; }
        public string area { get; set; }
        public string controller { get; set; }
        public string action { get; set; }
        public string icon_class { get; set; }
        public int sort { get; set; }
        public bool is_folder { get; set; }
        public bool is_use { get; set; }
        public bool is_on_tablet { get; set; }
        public bool is_only_tablet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetRoles> AspNetRoles { get; set; }
    }
}
